#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Prefer repo .env when run from the 9router checkout; override with ENV_FILE=...
ENV_FILE="${ENV_FILE:-.env}"

banner "2-PC local 9Router + Supabase sync"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm layout"
say "Goal: each PC runs a local Router; Clients use that PC's localhost; config stays aligned via Supabase SQLite sync."
warn "Do NOT point daily Clients at Render — that burns host egress and Fallback storms."
warn "Two PCs uploading the same SQLite every 30s = last-writer-wins. Prefer one PC online at a time, or pause sync on the idle PC."
step "Decide: is THIS machine PC1 (seed / primary) or PC2 (follower)?"
ask PC_ROLE "Type pc1 or pc2:"
note "You answered: $PC_ROLE"
pause "Press Enter when that role is correct for this run."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Install / run local Router"
say "You need a local Router on port 20128. Pick one path."
step "Option A (npm): npm install -g 9router && 9router"
step "Option B (this repo): npm install && npm run build && PORT=20128 HOSTNAME=0.0.0.0 npm run start"
step "Option C (Docker): docker run -d --name 9router -p 20128:20128 -v \"\$HOME/.9router:/app/data\" -e DATA_DIR=/app/data decolua/9router:latest"
open_url "http://localhost:20128/dashboard"
pause "Start the Router, open the dashboard (login if prompted), then press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Local .env basics"
say "These values go in $ENV_FILE for this machine (repo root or wherever you launch from)."
ask_secret JWT_SECRET "Paste or invent a long JWT_SECRET:"
ask_secret INITIAL_PASSWORD "Dashboard INITIAL_PASSWORD (first login):"
ask PORT "PORT [20128]:"
[[ -z "${PORT:-}" ]] && PORT=20128
ask BASE_URL "BASE_URL [http://localhost:20128]:"
[[ -z "${BASE_URL:-}" ]] && BASE_URL="http://localhost:20128"
ask DATA_DIR "DATA_DIR [leave empty for default ~/.9router]:"
write_env JWT_SECRET "$JWT_SECRET"
write_env INITIAL_PASSWORD "$INITIAL_PASSWORD"
write_env PORT "$PORT"
write_env BASE_URL "$BASE_URL"
write_env NEXT_PUBLIC_BASE_URL "$BASE_URL"
write_env CLOUD_URL "https://9router.com"
write_env NEXT_PUBLIC_CLOUD_URL "https://9router.com"
write_env NODE_ENV "production"
if [[ -n "${DATA_DIR:-}" ]]; then
  write_env DATA_DIR "$DATA_DIR"
fi
note "Restart the Router after .env changes so it picks them up."
pause "Restart done? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase project URL"
say "Same Supabase project on PC1 and PC2 so both restore/upload the same SQLite object."
open_url "https://supabase.com/dashboard"
step "Open (or create) your project → Project Settings → API."
step "Copy Project URL (https://xxxx.supabase.co)."
ask SUPABASE_URL "Paste SUPABASE_URL:"
write_env SUPABASE_URL "$SUPABASE_URL"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Supabase service role key"
say "Need the server secret that can write Storage — not the anon/publishable key."
step "Still on Project Settings → API: copy service_role (or sb_secret_…)."
warn "Never put this in NEXT_PUBLIC_*. Never commit it."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste SUPABASE_SERVICE_ROLE_KEY:"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Storage bucket"
say "Default bucket is 9router-data; object db/data.sqlite. App can create the bucket on upload."
step "Optional: Supabase → Storage → confirm bucket 9router-data exists (or let first upload create it)."
ask SUPABASE_BUCKET "SUPABASE_BUCKET [9router-data]:"
[[ -z "${SUPABASE_BUCKET:-}" ]] && SUPABASE_BUCKET="9router-data"
write_env SUPABASE_BUCKET "$SUPABASE_BUCKET"
write_env SUPABASE_OBJECT "db/data.sqlite"
ask SUPABASE_SYNC_MS "SUPABASE_SYNC_MS ms between uploads [30000]:"
[[ -z "${SUPABASE_SYNC_MS:-}" ]] && SUPABASE_SYNC_MS=30000
write_env SUPABASE_SYNC_MS "$SUPABASE_SYNC_MS"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify sync in logs"
say "Restart the Router with the new env, then watch logs."
step "Look for: [supabase-sync] restored … bytes  and/or  [supabase-sync] uploaded (boot)"
step "Also: [supabase-sync] every Ns → 9router-data/db/data.sqlite"
if [[ "${PC_ROLE,,}" == "pc2" ]]; then
  warn "PC2 should restore an existing remote DB if PC1 already uploaded."
else
  note "PC1 may start empty on first run, then upload after Connections exist."
fi
pause "Confirm those log lines, then press Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Providers + short combo"
open_url "http://localhost:20128/dashboard"
step "Providers: connect working Accounts (re-auth Claude if OAuth was revoked)."
step "Combos: keep Fallback short (avoid 6 free models × fat tool bodies per turn)."
step "Copy a dashboard API key for Clients (next stage)."
pause "Providers/combo look good? Press Enter (sync will upload on the interval)."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Point Clients at THIS PC"
say "Each PC's Claude Code / Cursor / Codex / Cline must use that machine's Router."
step "Endpoint: http://127.0.0.1:20128/v1  (prefer 127.0.0.1 over localhost on Windows)"
step "API Key: paste from the dashboard (do not commit it)."
ask_secret NINEROUTER_API_KEY "Paste dashboard API key (stored only in .env as a reminder):"
write_env NINEROUTER_API_KEY "$NINEROUTER_API_KEY"
note "Client apps keep their own key field — .env is just so you have a local copy."
pause "Client pointed at local /v1? Press Enter."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "PC2 checklist"
if [[ "${PC_ROLE,,}" == "pc1" ]]; then
  say "On the other PC: copy this wizard, re-run with role pc2, reuse the SAME Supabase URL + service_role."
  step "Copy SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_BUCKET from this .env (USB/password manager — not chat)."
  step "On PC2: run the wizard → pc2 → install Router → paste same Supabase secrets → Clients → 127.0.0.1:20128/v1"
  step "Avoid both PCs writing aggressively at once; last upload wins."
else
  say "You marked this machine PC2 — after restore, confirm Connections/combos match PC1 in the dashboard."
  step "If empty: wait for sync interval, or trigger by making a tiny settings change on PC1 and waiting for upload."
fi
pause "PC2 path clear? Press Enter to finish."

finish
say "Daily drive: local Router only. Render is optional backup, not the Client endpoint."
